"""
Discovery-Generated Trading Strategies

This package contains strategies automatically generated by AARA's
Discovery Engine through evolutionary optimization and hypothesis testing.

Strategies in this directory are:
- Automatically generated and validated
- Tracked with full lineage to their discovery process
- Subject to backtesting validation before deployment

See README.md for more information on how strategies are generated.
"""
