"""
Trading Strategies

This package contains trading strategy implementations organized by type:

- momentum/: Trend-following and momentum-based strategies
- mean_reversion/: Mean reversion and pairs trading strategies
- discovery_generated/: Strategies generated by AARA Discovery Engine

All strategies inherit from the BaseStrategy class and follow a consistent
interface for backtesting, paper trading, and live execution.

Usage:
    from verticals.trading.strategies import registry
    from verticals.trading.strategies.base import BaseStrategy
    
    # Get a registered strategy
    strategy = registry.get_strategy("simple_momentum")
    
    # Run strategy
    signals = strategy.generate_signals(market_data)
"""

from .base import BaseStrategy, StrategyConfig, Signal, SignalType

__all__ = ["BaseStrategy", "StrategyConfig", "Signal", "SignalType"]
